### ISSUE TITLE
ICUDriver on Arduino

### ISSUE THREAD

**Issue by JMOG94** [greiman/ChRt#2]
Hi I am Martín I am studying mechatronics and for one of my projects I need to know if there is compatibility with the Arduino ChibiOS and the ICUDriver, because I am trying to integrate the Ultrasonic Sensor (HC-SR04) with ChibiOS under this Arduino platform. An also I want to know if you have heard of other options to implement this kind of sensors that need the input capture unit.
I would appreciate any help or advice in this matter.
Grettings
Martín

**Comment by greiman** [comment]
See your other post
