### ISSUE TITLE
Both ChRt.c and ChRt.cpp in src ? (makes Atmel Studio failing)

### ISSUE THREAD

**Issue by PhiJu5** [greiman/ChRt#5]
In Arduino world, a .c file is ignored. Removing ChRt.c from src, ChBlink builds and run in Arduino IDE.
Import ChBlink in Atmel Studio works only if the (not usefull ?) ChRt.c is removed before import (because Atmel sutdio does handle both .c and .c++ files).
Regards.

**Comment by greiman** [comment]
ChRt.c is not ignored.  Any program will run without ChRt.c since it only provides LED blink codes for Hard faults, Bus erors, and Usage faults.

It is mostly helpful during my debug.
